services:

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  mqtt-service:
    build: ./mqtt-service
    restart: unless-stopped
    environment:
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_TOPIC: ${MQTT_TOPIC}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      BACKEND_BROADCAST_URL: http://backend:8000/internal/broadcast
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8090:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "4200:8080"
    depends_on:
      - backend
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
